import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/common/navbar";

const ppnuemontrealMedium = localFont({
  src: "../app/fonts/ppneuemontreal-medium.woff",
});
const ppnuemontrealBold = localFont({
  src: "../app/fonts/ppneuemontreal-bold.woff",
});

export const metadata: Metadata = {
  title: "Fruitful - Finances Figured Out for You, Get on Track in 30 Days",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta content="Feel great about your finances, finally. Work with a Fruitful Guide, take control of your money, and stop stressing. Get access to smarter, simpler ways to save and invest." />
      <meta content="Fruitful - Finances Figured Out for You, Get on Track in 30 Days" />
      <meta content="Feel great about your finances, finally. Work with a Fruitful Guide, take control of your money, and stop stressing. Get access to smarter, simpler ways to save and invest." />
      <meta
        content="https://d1pwidzl9kib4u.cloudfront.net/marketing/web/Fruitful_Opengraph.jpg"
        property="og:image"
      />
      <meta
        content="Fruitful - Finances Figured Out for You, Get on Track in 30 Days"
        property="twitter:title"
      />
      <meta content="Feel great about your finances, finally. Work with a Fruitful Guide, take control of your money, and stop stressing. Get access to smarter, simpler ways to save and invest." />
      <meta
        content="https://d1pwidzl9kib4u.cloudfront.net/marketing/web/Fruitful_Opengraph.jpg"
        property="twitter:image"
      />
      <meta property="og:type" content="website" />
      <meta content="summary_large_image" name="twitter:card" />
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <body
        className={`${ppnuemontrealMedium.className} antialiased selection:bg-green-900 selection:text-green-200`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
